apiVersion: v1
kind: Namespace
metadata:
  name: iasc
---
apiVersion: v1
kind: Pod
metadata:
  name: iasckub-manual
  namespace: iasc
spec:
  containers:
  - image: iascfrba/iasckub:latest
    name: iasckub
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 128Mi
        cpu: "0.2"
      requests:
        memory: 64Mi
        cpu: "0.1"      