apiVersion: v1
kind: Namespace
metadata:
  name: iasc-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: iasckub-manual
  namespace: iasc-namespace
spec:
  containers:
  - image: iascfrba/iasckub:latest
    name: iasckub
    ports:
    - containerPort: 8080
      protocol: TCP