apiVersion: v1
kind: Namespace
metadata:
  name: iasc
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iasckub-deployment
  namespace: iasc
spec:
  selector:
    matchLabels:
      app: iasckub
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: iasckub
    spec:
      containers:
      - name: iasckub
        image: iascfrba/iasckub:latest
        ports:
        - containerPort: 8080