apiVersion: apps/v1
kind: Deployment
metadata:
  name: iasckub-deployment
  namespace: iasc
spec:
  selector:
    matchLabels:
      app: iasckub
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: iasckub
    spec:
      containers:
        - name: iasckub
          image: iascfrba/iasckub:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 275Mi
              cpu: "0.35"
            requests:
              memory: 128Mi
              cpu: "0.2"    
