apiVersion: v1
kind: Namespace
metadata:
  name: iasc
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iasckub-deployment
  namespace: iasc
spec:
  selector:
    matchLabels:
      app: iasckub
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: iasckub
    spec:
      containers:
        - name: iasckub
          image: iascfrba/iasckub:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 256Mi
              cpu: "0.3"
            requests:
              memory: 64Mi
              cpu: "0.1"    
