---
apiVersion: v1
kind: Namespace
metadata:
  name: iasc
---
kind: Service
apiVersion: v1
metadata:
  name: iasc-service
  namespace: iasc
spec:
  type: LoadBalancer
  selector:
    app: iasc-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iasc-service
  namespace: iasc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iasc-service
  template:
    metadata:
      labels:
        app: iasc-service
    spec:
      containers:
      - name: iasc-service
        image: iascfrba/iasckub:v3
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 25
          failureThreshold: 5
          periodSeconds: 90  
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            cpu: 200m   
---          