---
apiVersion: v1
kind: Namespace
metadata:
  name: iasc
---
kind: Service
apiVersion: v1
metadata:
  name: iasc-service
  namespace: iasc
spec:
  type: LoadBalancer
  selector:
    app: iasc-service
  clusterIP: 10.111.179.124
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iasc-service
  namespace: iasc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iasc-service
  template:
    metadata:
      labels:
        app: iasc-service
    spec:
      containers:
      - name: iasc-service
        image: iascfrba/iasckub:v3
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 25
          failureThreshold: 3
          periodSeconds: 10  
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: 200m    
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: iasc-service-autoscaler
  namespace: iasc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iasc-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
---  