apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: iasc-service-autoscaler
  namespace: iasc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iasc-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---  