apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: iasc
spec:
  containers:
  - image: busybox
    name: load-generator
    command:
      - /bin/sh
      - -c
      - "while true; do wget -q -O- http://iasc-service/fib; done"
    imagePullPolicy: IfNotPresent  
  restartPolicy: Always