apiVersion: v1
kind: Namespace
metadata:
  name: iasc
---  
apiVersion: v1
kind: Pod
metadata:
  name: iasckub-liveness
  namespace: iasc
spec:
  containers:
  - image: iascfrba/iasckub
    name: iasckub
    ports:
      - containerPort: 8080
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      failureThreshold: 3
      periodSeconds: 10
    resources:
      limits:
        memory: 256Mi
        cpu: "0.5"
      requests:
        memory: 128Mi
        cpu: "0.2"      
---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
  namespace: iasc
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: iascfrba/iasc-busybox
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job-every-fifteen-minutes
  namespace: iasc
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: iascfrba/iasc-busybox